In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
dframe = DataFrame(np.arange(16).reshape((4, 4)))

In [4]:
blender = np.random.permutation(4)

In [5]:
blender

array([3, 2, 0, 1])

In [6]:
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [7]:
dframe.take(blender)

0   1   2   3
3  12  13  14  15
2   8   9  10  11
0   0   1   2   3
1   4   5   6   7

In [9]:
box = np.array([1,2,3])

In [10]:
shaker = np.random.randint(0,len(box),size=10)

In [11]:
shaker

array([2, 0, 2, 2, 1, 1, 0, 2, 0, 0])

In [14]:
hand_grabs = box.take(shaker)
hand_grabs

array([3, 1, 3, 3, 2, 2, 1, 3, 1, 1])